### ISSUE TITLE
Circular dependence

### ISSUE THREAD

**Issue by benman1** [parrt/stratx#5]
Hi
I've tried this with versions 0.4.1 and 0.4.1. Both fail with the same problem when I try to import:
`from stratx.partdep import plot_stratpd`

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-4a26e9213130> in <module>()
      1 import matplotlib.pyplot as plt
----> 2 from stratx.partdep import plot_stratpd
      3 
      4 fig, axes = plt.subplots(4, 3, figsize= (11, 16), sharey=True)
      5 for col, ax in zip(data_ames[num_cols], axes.flat):

1 frames
/usr/local/lib/python3.6/dist-packages/stratx/partdep.py in <module>()
     37 from numba import jit, prange
     38 
---> 39 import stratx.featimp as featimp
     40 
     41 

/usr/local/lib/python3.6/dist-packages/stratx/featimp.py in <module>()
     32 from matplotlib.patches import Rectangle
     33 
---> 34 import stratx.partdep as partdep
     35 import stratx.ice as ice
     36 

AttributeError: module 'stratx' has no attribute 'partdep'
```

**Comment by parrt** [comment]
Hi. Dang. I need to clean up the package refs I guess. grrr.. sorry about that.

**Comment by parrt** [comment]
Just tried this and seems ok:

```
beast:/private/tmp $ python t.py
beast:/private/tmp $ pip list |grep stratx
stratx                             0.4.1
beast:/private/tmp $ cat t.py
from stratx.partdep import plot_stratpd
```

Oh! Is your file called stratx.py?

**Comment by benman1** [comment]
No, that's not it. Also the error wouldn't make sense then. The first import would have failed.

You see, the partdep module uses the featimp module and the featimp module uses the partdep module. This shouldn't work at all.

**Comment by parrt** [comment]
hmm...yeah,  not sure why mine works then.  I did have cyclic dependencies problems early on but I thought I fixed it by being very specific with what I pulled in.  Can you explain why mine works and yours doesn't?

**Comment by parrt** [comment]
I think the right answer is for me to change the stratx package `__init.py__` so that it imports all of the user interface level functions directly.

**Comment by benman1** [comment]
Have a look: 

```python
Apples-MacBook-Air:~ ben$ pip install 'stratx==0.4.1'
Requirement already satisfied: stratx==0.4.1 in ./anaconda3/lib/python3.6/site-packages (0.4.1)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.6/site-packages (from stratx==0.4.1) (1.19.1)
Requirement already satisfied: numba in ./anaconda3/lib/python3.6/site-packages (from stratx==0.4.1) (0.50.1)
Requirement already satisfied: pandas in ./anaconda3/lib/python3.6/site-packages (from stratx==0.4.1) (1.1.0)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.6/site-packages (from stratx==0.4.1) (1.5.2)
Requirement already satisfied: scikit-learn in ./anaconda3/lib/python3.6/site-packages (from stratx==0.4.1) (0.22.2.post1)
Requirement already satisfied: colour in ./anaconda3/lib/python3.6/site-packages (from stratx==0.4.1) (0.1.5)
Requirement already satisfied: matplotlib in ./.local/lib/python3.6/site-packages (from stratx==0.4.1) (3.2.2)
Requirement already satisfied: llvmlite<0.34,>=0.33.0.dev0 in ./anaconda3/lib/python3.6/site-packages (from numba->stratx==0.4.1) (0.33.0)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from numba->stratx==0.4.1) (49.6.0.post20200814)
Requirement already satisfied: python-dateutil>=2.7.3 in ./anaconda3/lib/python3.6/site-packages (from pandas->stratx==0.4.1) (2.7.5)
Requirement already satisfied: pytz>=2017.2 in ./anaconda3/lib/python3.6/site-packages (from pandas->stratx==0.4.1) (2018.7)
Requirement already satisfied: joblib>=0.11 in ./anaconda3/lib/python3.6/site-packages (from scikit-learn->stratx==0.4.1) (0.16.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./anaconda3/lib/python3.6/site-packages (from matplotlib->stratx==0.4.1) (2.4.7)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.6/site-packages (from matplotlib->stratx==0.4.1) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/lib/python3.6/site-packages (from matplotlib->stratx==0.4.1) (1.0.1)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas->stratx==0.4.1) (1.15.0)
Apples-MacBook-Air:~ ben$ python t
python: can't open file 't': [Errno 2] No such file or directory
Apples-MacBook-Air:~ ben$ python t.py
Traceback (most recent call last):
  File "t.py", line 1, in <module>
    from stratx.partdep import plot_stratpd
  File "/Users/ben/anaconda3/lib/python3.6/site-packages/stratx/partdep.py", line 39, in <module>
    import stratx.featimp as featimp
  File "/Users/ben/anaconda3/lib/python3.6/site-packages/stratx/featimp.py", line 34, in <module>
    import stratx.partdep as partdep
AttributeError: module 'stratx' has no attribute 'partdep'
Apples-MacBook-Air:~ ben$ cat t.py
from stratx.partdep import plot_stratpd
```

I suggest you reinstall the library from scratch and try then.

**Comment by benman1** [comment]
Just putting the user interface functions in an import in __init__.py wouldn't help. It would still fail.

The problem is the interdependence. You could have one file with everything. That would work (but it'd be a bit ugly). Alternatively, you could have utility functions (say utilities.py) accessed by both partdep and featimp.

**Comment by parrt** [comment]
complete un/re- install still works for me.  so I'm not sure what's going on there but both notebooks and standalone Python files work for me. Could it be the version of Python? I'm at 3.8 I think.

**Comment by benman1** [comment]
When you say complete uninstall, reinstall are you making sure, you are not
importing from a local strax directory?

Le ven. 18 sept. 2020 à 18:18, Terence Parr <notifications@github.com> a
écrit :

**Comment by parrt** [comment]
My history:
```
  512  pip uninstall stratx
  513  pip install stratx
  514  python t.py
```

```
beast:/private/tmp $ pwd
/private/tmp
```

**Comment by benman1** [comment]
I am really puzzled now. Could you try on colab? colab.research.google.com/

Le ven. 18 sept. 2020 à 18:29, Terence Parr <notifications@github.com> a
écrit :

**Comment by parrt** [comment]
Wow. colab has the problem you indicate. Any ideas what the diff might be?

**Comment by benman1** [comment]
Good that we could reproduce it. I suspect that you didn't completely
remove the library. Your version must be still somewhere in your python
path. You could try something like `python -v t.py` to see from where you
import.

Le ven. 18 sept. 2020 à 19:49, Terence Parr <notifications@github.com> a
écrit :

**Comment by parrt** [comment]
it looks like it's pulling from a cache that might not actually be wiped out with an uninstall.  that would surprise me, but I will wipe the cache and try again.  still works. hmm... i'm in /tmp. Ugh.  anyway, thanks for reporting this. Next time I take a pass on the software I will try to remove the circular dependencies. damn python.

**Comment by benman1** [comment]
If it's the cache, you can pip install with options --no-cache-dir and -U.
I suspect `pip install-U strax` might be enough.

It's a very cool library, and it fills an important niche. I am surprised
nobody else found it. I went back a bit through commits. This problem must
have been there for a while. If I could suggest something, it'd be to
integrate it with another data visualization library.

Le ven. 18 sept. 2020 à 20:20, Terence Parr <notifications@github.com> a
écrit :

**Comment by parrt** [comment]
Glad you like it; yeah, the idea is a cool trick. Have you seen my https://github.com/parrt/dtreeviz library?  

I'll definitely clean this up when the papers come back from peer review. thanks! 

still seems to be an issue after uninstall then:

```
beast:/private/tmp $ pip install --no-cache-dir -U stratx
Collecting stratx
  Downloading stratx-0.4.1.tar.gz (160 kB)
     |████████████████████████████████| 160 kB 11.2 MB/s 
Requirement already satisfied, skipping upgrade: scikit-learn in
...
Installing collected packages: stratx
Successfully installed stratx-0.4.1
beast:/private/tmp $ python t.py
beast:/private/tmp $ 
```

**Comment by benman1** [comment]
Yes, I've seen your other libraries, useful stuff. Good luck with the
reviews!


Le ven. 18 sept. 2020 à 20:51, Terence Parr <notifications@github.com> a
écrit :

**Comment by parrt** [comment]
@benman1 please check out https://colab.research.google.com/github/parrt/stratx/blob/master/notebooks/examples.ipynb  I think I fixed it in a 0.5 release just now.

Fixed by efe245741c5d4587ebd1833fc8e00d7c72cace40

**Comment by benman1** [comment]
Seems ok now. Thanks for fixing!

```
Apples-MacBook-Air:~ ben$ python t.py
Apples-MacBook-Air:~ ben$ cat t.py
from stratx import plot_stratpd
Apples-MacBook-Air:~ ben$ pip freeze | grep stratx
stratx==0.5
```

**Comment by parrt** [comment]
Great!   Let me know if you have problems.  I think I'm the only one who's tried stratx ;)

**Comment by benman1** [comment]
I hope not. I think the python ecosystem of visualization libraries around machine learning/data science is fragmented, so it's maybe not easy to find good tools.
